---
k3s_version: v1.18.9+k3s1
ansible_user: pi
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_python_interpreter: /usr/bin/python3
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
#extra_server_args: "--tls-san {{ ip }}"
extra_agent_args: ""
